export const CROP_YIELD_PROFILE = {

  /* ===================== Cereals & Millets ===================== */
  wheat:        { category: "cereal",  baseYieldPerHa: 45, unit: "quintal" },
  rice:         { category: "cereal",  baseYieldPerHa: 50, unit: "quintal" },
  corn:         { category: "cereal",  baseYieldPerHa: 60, unit: "quintal" },
  barley:       { category: "cereal",  baseYieldPerHa: 40, unit: "quintal" },
  pearlmillet:  { category: "cereal",  baseYieldPerHa: 25, unit: "quintal" },
  sorghum:      { category: "cereal",  baseYieldPerHa: 30, unit: "quintal" },
  fingermillet: { category: "cereal",  baseYieldPerHa: 20, unit: "quintal" },
  oats:         { category: "cereal",  baseYieldPerHa: 30, unit: "quintal" },
  rye:          { category: "cereal",  baseYieldPerHa: 25, unit: "quintal" },
  quinoa:       { category: "cereal",  baseYieldPerHa: 18, unit: "quintal" },
  buckwheat:    { category: "cereal",  baseYieldPerHa: 12, unit: "quintal" },
  triticale:    { category: "cereal",  baseYieldPerHa: 40, unit: "quintal" },
  teff:         { category: "cereal",  baseYieldPerHa: 10, unit: "quintal" },
  amaranthgrain:{ category: "cereal",  baseYieldPerHa: 15, unit: "quintal" },

  /* ===================== Pulses ===================== */
  chickpea:        { category: "pulse", baseYieldPerHa: 18, unit: "quintal" },
  greengram:       { category: "pulse", baseYieldPerHa: 12, unit: "quintal" },
  blackgram:       { category: "pulse", baseYieldPerHa: 12, unit: "quintal" },
  lentil:          { category: "pulse", baseYieldPerHa: 14, unit: "quintal" },
  horsegram:       { category: "pulse", baseYieldPerHa: 10, unit: "quintal" },
  cowpealobia:     { category: "pulse", baseYieldPerHa: 15, unit: "quintal" },
  kidneybeansrajma:{ category: "pulse", baseYieldPerHa: 20, unit: "quintal" },
  redgram:         { category: "pulse", baseYieldPerHa: 18, unit: "quintal" },
  greenpeas:       { category: "pulse", baseYieldPerHa: 20, unit: "quintal" },
  beans:           { category: "pulse", baseYieldPerHa: 18, unit: "quintal" },
  guarclusterbean: { category: "pulse", baseYieldPerHa: 10, unit: "quintal" },

  /* ===================== Oilseeds ===================== */
  soybean:   { category: "oilseed", baseYieldPerHa: 25, unit: "quintal" },
  groundnut:{ category: "oilseed", baseYieldPerHa: 30, unit: "quintal" },
  mustard:  { category: "oilseed", baseYieldPerHa: 18, unit: "quintal" },
  sunflower:{ category: "oilseed", baseYieldPerHa: 20, unit: "quintal" },
  sesame:   { category: "oilseed", baseYieldPerHa: 10, unit: "quintal" },
  linseed:  { category: "oilseed", baseYieldPerHa: 12, unit: "quintal" },
  castor:   { category: "oilseed", baseYieldPerHa: 15, unit: "quintal" },
  safflower:{ category: "oilseed", baseYieldPerHa: 12, unit: "quintal" },
  niger:    { category: "oilseed", baseYieldPerHa: 8,  unit: "quintal" },
  chia:     { category: "oilseed", baseYieldPerHa: 8,  unit: "quintal" },
  canolarapeseed: { category: "oilseed", baseYieldPerHa: 22, unit: "quintal" },

  /* ===================== Vegetables ===================== */
  tomato:      { category: "vegetable", baseYieldPerHa: 30, unit: "tons" },
  potato:     { category: "vegetable", baseYieldPerHa: 25, unit: "tons" },
  onion:      { category: "vegetable", baseYieldPerHa: 20, unit: "tons" },
  garlic:     { category: "vegetable", baseYieldPerHa: 8,  unit: "tons" },
  brinjal:    { category: "vegetable", baseYieldPerHa: 28, unit: "tons" },
  cabbage:    { category: "vegetable", baseYieldPerHa: 35, unit: "tons" },
  cauliflower:{ category: "vegetable", baseYieldPerHa: 25, unit: "tons" },
  carrot:     { category: "vegetable", baseYieldPerHa: 30, unit: "tons" },
  beetroot:   { category: "vegetable", baseYieldPerHa: 25, unit: "tons" },
  radish:     { category: "vegetable", baseYieldPerHa: 30, unit: "tons" },
  cucumber:   { category: "vegetable", baseYieldPerHa: 20, unit: "tons" },
  pumpkin:    { category: "vegetable", baseYieldPerHa: 18, unit: "tons" },
  okra:       { category: "vegetable", baseYieldPerHa: 15, unit: "tons" },
  spinach:    { category: "vegetable", baseYieldPerHa: 12, unit: "tons" },
  lettuce:    { category: "vegetable", baseYieldPerHa: 10, unit: "tons" },
  capsicum:   { category: "vegetable", baseYieldPerHa: 20, unit: "tons" },
  broccoli:   { category: "vegetable", baseYieldPerHa: 18, unit: "tons" },
  bittergourd:{ category: "vegetable", baseYieldPerHa: 15, unit: "tons" },
  bottlegourd:{ category: "vegetable", baseYieldPerHa: 20, unit: "tons" },
  spongegourd:{ category: "vegetable", baseYieldPerHa: 18, unit: "tons" },
  ashgourd:   { category: "vegetable", baseYieldPerHa: 25, unit: "tons" },
  snakegourd: { category: "vegetable", baseYieldPerHa: 18, unit: "tons" },
  longmelon:  { category: "vegetable", baseYieldPerHa: 18, unit: "tons" },
  squashmelon:{ category: "vegetable", baseYieldPerHa: 20, unit: "tons" },
  summersquash:{ category: "vegetable", baseYieldPerHa: 18, unit: "tons" },
  sweetpotato:{ category: "vegetable", baseYieldPerHa: 20, unit: "tons" },
  turnip:     { category: "vegetable", baseYieldPerHa: 25, unit: "tons" },
  mushroom:   { category: "vegetable", baseYieldPerHa: 18, unit: "tons" },
  celery:    { category: "vegetable", baseYieldPerHa: 12, unit: "tons" },
  chilli:    { category: "vegetable", baseYieldPerHa: 12, unit: "tons" },
  drumstick: { category: "vegetable", baseYieldPerHa: 25, unit: "tons" },
  sugarbeet: { category: "vegetable", baseYieldPerHa: 70, unit: "tons" },

  /* ===================== Fruits ===================== */
  banana:      { category: "fruit", baseYieldPerHa: 35, unit: "tons" },
  papaya:      { category: "fruit", baseYieldPerHa: 40, unit: "tons" },
  mango:       { category: "fruit", baseYieldPerHa: 10, unit: "tons" },
  guava:       { category: "fruit", baseYieldPerHa: 15, unit: "tons" },
  pomegranate: { category: "fruit", baseYieldPerHa: 12, unit: "tons" },
  grapes:      { category: "fruit", baseYieldPerHa: 20, unit: "tons" },
  watermelon:  { category: "fruit", baseYieldPerHa: 30, unit: "tons" },
  muskmelon:   { category: "fruit", baseYieldPerHa: 25, unit: "tons" },
  orange:      { category: "fruit", baseYieldPerHa: 18, unit: "tons" },
  sapota:      { category: "fruit", baseYieldPerHa: 10, unit: "tons" },
  fig:         { category: "fruit", baseYieldPerHa: 8,  unit: "tons" },
  apple:       { category: "fruit", baseYieldPerHa: 10, unit: "tons" },
  lemon:       { category: "fruit", baseYieldPerHa: 15, unit: "tons" },
  pineapple:   { category: "fruit", baseYieldPerHa: 45, unit: "tons" },
  kiwi:        { category: "fruit", baseYieldPerHa: 7,  unit: "tons" },
  amla:        { category: "fruit", baseYieldPerHa: 8,  unit: "tons" },
  dragonfruit: { category: "fruit", baseYieldPerHa: 20, unit: "tons" },
  pears:       { category: "fruit", baseYieldPerHa: 22, unit: "tons" },
  winegrapes:  { category: "fruit", baseYieldPerHa: 10, unit: "tons" },
  tablegrapes: { category: "fruit", baseYieldPerHa: 28, unit: "tons" },
  citrus:      { category: "fruit", baseYieldPerHa: 18, unit: "tons" },
  cherry:      { category: "fruit", baseYieldPerHa: 12, unit: "tons" },
  peach:       { category: "fruit", baseYieldPerHa: 20, unit: "tons" },
  avocado:     { category: "fruit", baseYieldPerHa: 12, unit: "tons" },
  olive:       { category: "fruit", baseYieldPerHa: 8,  unit: "tons" },
  plum:        { category: "fruit", baseYieldPerHa: 16, unit: "tons" },
  apricot:     { category: "fruit", baseYieldPerHa: 14, unit: "tons" },
  nectarine:   { category: "fruit", baseYieldPerHa: 18, unit: "tons" },
  blueberry:   { category: "fruit", baseYieldPerHa: 10, unit: "tons" },
  raspberry:   { category: "fruit", baseYieldPerHa: 10, unit: "tons" },
  blackberry:  { category: "fruit", baseYieldPerHa: 12, unit: "tons" },
  cranberry:   { category: "fruit", baseYieldPerHa: 20, unit: "tons" },
  persimmon:   { category: "fruit", baseYieldPerHa: 16, unit: "tons" },
  lychee:      { category: "fruit", baseYieldPerHa: 10, unit: "tons" },
  rambutan:    { category: "fruit", baseYieldPerHa: 12, unit: "tons" },
  durian:      { category: "fruit", baseYieldPerHa: 10, unit: "tons" },
  jackfruit:   { category: "fruit", baseYieldPerHa: 20, unit: "tons" },
  custardapple:{ category: "fruit", baseYieldPerHa: 10, unit: "tons" },
  passionfruit:{ category: "fruit", baseYieldPerHa: 25, unit: "tons" },
  starfruit:   { category: "fruit", baseYieldPerHa: 18, unit: "tons" },
  datepalm:    { category: "fruit", baseYieldPerHa: 12, unit: "tons" },

  /* ===================== Nuts ===================== */
  pecannuts:     { category: "nut", baseYieldPerHa: 3,   unit: "tons" },
  macadamianuts: { category: "nut", baseYieldPerHa: 4,   unit: "tons" },
  almond:        { category: "nut", baseYieldPerHa: 2,   unit: "tons" },
  walnut:        { category: "nut", baseYieldPerHa: 3,   unit: "tons" },
  cashew:        { category: "nut", baseYieldPerHa: 1,   unit: "tons" },
  pistachio:     { category: "nut", baseYieldPerHa: 2,   unit: "tons" },
  hazelnut:      { category: "nut", baseYieldPerHa: 2,   unit: "tons" },
  chestnut:      { category: "nut", baseYieldPerHa: 2,   unit: "tons" },
  brazilnut:     { category: "nut", baseYieldPerHa: 1,   unit: "tons" },
  pinenut:       { category: "nut", baseYieldPerHa: 0.5, unit: "tons" },

  /* ===================== Plantation & Spices ===================== */
  turmeric:    { category: "spice", baseYieldPerHa: 25, unit: "tons" },
  ginger:      { category: "spice", baseYieldPerHa: 20, unit: "tons" },
  coriander:   { category: "spice", baseYieldPerHa: 15, unit: "quintal" },
  cumin:       { category: "spice", baseYieldPerHa: 8,  unit: "quintal" },
  fenugreekmethi:{ category: "spice", baseYieldPerHa: 12, unit: "quintal" },
  blackpepper: { category: "plantation", baseYieldPerHa: 2, unit: "tons" },
  tea:         { category: "plantation", baseYieldPerHa: 2, unit: "tons" },
  coffee:      { category: "plantation", baseYieldPerHa: 1.5, unit: "tons" },
  coconut:     { category: "plantation", baseYieldPerHa: 10, unit: "tons" },
  arecanut:    { category: "plantation", baseYieldPerHa: 12, unit: "tons" },
  rubber:      { category: "plantation", baseYieldPerHa: 2, unit: "tons" },
  cacaococoa:  { category: "plantation", baseYieldPerHa: 1, unit: "tons" },
  vanilla:     { category: "plantation", baseYieldPerHa: 0.4, unit: "tons" },
  oilpalm:     { category: "plantation", baseYieldPerHa: 22, unit: "tons" },
  hemp:        { category: "plantation", baseYieldPerHa: 10, unit: "tons" },

  /* ===================== Forage / Fodder ===================== */
  lucernealfalfa: { category: "forage", baseYieldPerHa: 90,  unit: "tons" },
  feedsorghum:    { category: "forage", baseYieldPerHa: 60,  unit: "tons" },
  berseem:        { category: "forage", baseYieldPerHa: 70,  unit: "tons" },
  napiergrass:    { category: "forage", baseYieldPerHa: 200, unit: "tons" },
  covercrop:      { category: "forage", baseYieldPerHa: 0,   unit: "tons" },

  /* ===================== Commercial ===================== */
  sugarcane: { category: "cereal", baseYieldPerHa: 75, unit: "tons" },
  cotton:    { category: "oilseed", baseYieldPerHa: 20, unit: "quintal" },
  tobacco:   { category: "vegetable", baseYieldPerHa: 18, unit: "quintal" },
  jute:      { category: "cereal", baseYieldPerHa: 25, unit: "quintal" },

  /* ===================== New crops (65-crop expansion) ===================== */

  /* ----- Flower ----- */
  rose: { category: "flower", baseYieldPerHa: 12, unit: "tons" },
  marigold: { category: "flower", baseYieldPerHa: 15, unit: "tons" },
  jasmine: { category: "flower", baseYieldPerHa: 8, unit: "tons" },
  chrysanthemum: { category: "flower", baseYieldPerHa: 12, unit: "tons" },
  tuberose: { category: "flower", baseYieldPerHa: 10, unit: "tons" },
  hibiscus: { category: "flower", baseYieldPerHa: 8, unit: "tons" },
  gerbera: { category: "flower", baseYieldPerHa: 250, unit: "tons" },
  carnation: { category: "flower", baseYieldPerHa: 200, unit: "tons" },
  gladiolus: { category: "flower", baseYieldPerHa: 300, unit: "tons" },
  orchid: { category: "flower", baseYieldPerHa: 150, unit: "tons" },
  anthurium: { category: "flower", baseYieldPerHa: 120, unit: "tons" },
  lily: { category: "flower", baseYieldPerHa: 180, unit: "tons" },
  tulip: { category: "flower", baseYieldPerHa: 200, unit: "tons" },
  dahlia: { category: "flower", baseYieldPerHa: 15, unit: "tons" },
  aster: { category: "flower", baseYieldPerHa: 10, unit: "tons" },
  lavender: { category: "flower", baseYieldPerHa: 3, unit: "tons" },
  zinnia: { category: "flower", baseYieldPerHa: 10, unit: "tons" },
  petunia: { category: "flower", baseYieldPerHa: 8, unit: "tons" },
  poinsettia: { category: "flower", baseYieldPerHa: 100, unit: "tons" },

  /* ----- Herb ----- */
  basil: { category: "herb", baseYieldPerHa: 20, unit: "tons" },
  mint: { category: "herb", baseYieldPerHa: 25, unit: "tons" },
  lemongrass: { category: "herb", baseYieldPerHa: 30, unit: "tons" },
  aloevera: { category: "herb", baseYieldPerHa: 40, unit: "tons" },
  stevia: { category: "herb", baseYieldPerHa: 8, unit: "tons" },
  ashwagandha: { category: "herb", baseYieldPerHa: 6, unit: "quintal" },
  rosemary: { category: "herb", baseYieldPerHa: 10, unit: "tons" },
  thyme: { category: "herb", baseYieldPerHa: 8, unit: "tons" },
  oregano: { category: "herb", baseYieldPerHa: 10, unit: "tons" },
  chamomile: { category: "herb", baseYieldPerHa: 5, unit: "tons" },

  /* ----- Spice ----- */
  cardamom: { category: "spice", baseYieldPerHa: 0.3, unit: "tons" },
  clove: { category: "spice", baseYieldPerHa: 1.5, unit: "tons" },
  nutmeg: { category: "spice", baseYieldPerHa: 1, unit: "tons" },
  cinnamon: { category: "spice", baseYieldPerHa: 2, unit: "tons" },
  saffron: { category: "spice", baseYieldPerHa: 0.005, unit: "tons" },
  staranise: { category: "spice", baseYieldPerHa: 1.5, unit: "tons" },

  /* ----- Vegetable (roots/tubers & greens) ----- */
  cassava: { category: "vegetable", baseYieldPerHa: 30, unit: "tons" },
  taro: { category: "vegetable", baseYieldPerHa: 20, unit: "tons" },
  yam: { category: "vegetable", baseYieldPerHa: 25, unit: "tons" },
  arrowroot: { category: "vegetable", baseYieldPerHa: 15, unit: "tons" },
  asparagus: { category: "vegetable", baseYieldPerHa: 6, unit: "tons" },
  artichoke: { category: "vegetable", baseYieldPerHa: 12, unit: "tons" },
  kale: { category: "vegetable", baseYieldPerHa: 25, unit: "tons" },
  brusselssprouts: { category: "vegetable", baseYieldPerHa: 20, unit: "tons" },
  leek: { category: "vegetable", baseYieldPerHa: 25, unit: "tons" },
  fennel: { category: "vegetable", baseYieldPerHa: 20, unit: "tons" },
  bokchoy: { category: "vegetable", baseYieldPerHa: 25, unit: "tons" },
  chicory: { category: "vegetable", baseYieldPerHa: 25, unit: "tons" },

  /* ----- Fruit ----- */
  mandarin: { category: "fruit", baseYieldPerHa: 20, unit: "tons" },
  pomelo: { category: "fruit", baseYieldPerHa: 18, unit: "tons" },
  mangosteen: { category: "fruit", baseYieldPerHa: 8, unit: "tons" },
  soursop: { category: "fruit", baseYieldPerHa: 10, unit: "tons" },
  tamarind: { category: "fruit", baseYieldPerHa: 10, unit: "tons" },
  longan: { category: "fruit", baseYieldPerHa: 10, unit: "tons" },
  breadfruit: { category: "fruit", baseYieldPerHa: 15, unit: "tons" },
  redcurrant: { category: "fruit", baseYieldPerHa: 8, unit: "tons" },
  gooseberry: { category: "fruit", baseYieldPerHa: 8, unit: "tons" },
  elderberry: { category: "fruit", baseYieldPerHa: 10, unit: "tons" },

  /* ----- Pulse ----- */
  fababean: { category: "pulse", baseYieldPerHa: 25, unit: "quintal" },
  limabean: { category: "pulse", baseYieldPerHa: 15, unit: "quintal" },
  adzukibean: { category: "pulse", baseYieldPerHa: 15, unit: "quintal" },
  lupin: { category: "pulse", baseYieldPerHa: 20, unit: "quintal" },

  /* ----- Cereal / fiber ----- */
  kenaf: { category: "cereal", baseYieldPerHa: 20, unit: "tons" },
  sisal: { category: "cereal", baseYieldPerHa: 3, unit: "tons" },
  flaxfiber: { category: "cereal", baseYieldPerHa: 8, unit: "tons" },

  /* ----- Plantation ----- */
  yerbamate: { category: "plantation", baseYieldPerHa: 3, unit: "tons" },

  /* ===================== Fallback ===================== */
  default: { category: "vegetable", baseYieldPerHa: 5, unit: "tons" },
};

// Crop-encyclopedia name aliases — see the matching comment in
// src/utils/npk/cropProfiles.js for why these are needed.
CROP_YIELD_PROFILE.fenugreek = CROP_YIELD_PROFILE.fenugreekmethi;
CROP_YIELD_PROFILE.citrusgeneric = CROP_YIELD_PROFILE.citrus;
CROP_YIELD_PROFILE.covercropgenericmix = CROP_YIELD_PROFILE.covercrop;
