export const CROP_YIELD_PROFILE = {

  /* ===================== Cereals & Millets ===================== */
  wheat:        { category: "cereal",  baseYieldPerHa: 45, unit: "quintal" },
  rice:         { category: "cereal",  baseYieldPerHa: 50, unit: "quintal" },
  corn:         { category: "cereal",  baseYieldPerHa: 60, unit: "quintal" },
  barley:       { category: "cereal",  baseYieldPerHa: 40, unit: "quintal" },
  pearlmillet:  { category: "cereal",  baseYieldPerHa: 25, unit: "quintal" },
  sorghum:      { category: "cereal",  baseYieldPerHa: 30, unit: "quintal" },
  fingermillet: { category: "cereal",  baseYieldPerHa: 20, unit: "quintal" },

  /* ===================== Pulses ===================== */
  chickpea:        { category: "pulse", baseYieldPerHa: 18, unit: "quintal" },
  greengram:       { category: "pulse", baseYieldPerHa: 12, unit: "quintal" },
  blackgram:       { category: "pulse", baseYieldPerHa: 12, unit: "quintal" },
  lentil:          { category: "pulse", baseYieldPerHa: 14, unit: "quintal" },
  horsegram:       { category: "pulse", baseYieldPerHa: 10, unit: "quintal" },
  cowpealobia:     { category: "pulse", baseYieldPerHa: 15, unit: "quintal" },
  kidneybeansrajma:{ category: "pulse", baseYieldPerHa: 20, unit: "quintal" },
  redgram:         { category: "pulse", baseYieldPerHa: 18, unit: "quintal" },
  greenpeas:       { category: "pulse", baseYieldPerHa: 20, unit: "quintal" },
  beans:           { category: "pulse", baseYieldPerHa: 18, unit: "quintal" },

  /* ===================== Oilseeds ===================== */
  soybean:   { category: "oilseed", baseYieldPerHa: 25, unit: "quintal" },
  groundnut:{ category: "oilseed", baseYieldPerHa: 30, unit: "quintal" },
  mustard:  { category: "oilseed", baseYieldPerHa: 18, unit: "quintal" },
  sunflower:{ category: "oilseed", baseYieldPerHa: 20, unit: "quintal" },
  sesame:   { category: "oilseed", baseYieldPerHa: 10, unit: "quintal" },
  linseed:  { category: "oilseed", baseYieldPerHa: 12, unit: "quintal" },
  castor:   { category: "oilseed", baseYieldPerHa: 15, unit: "quintal" },
  safflower:{ category: "oilseed", baseYieldPerHa: 12, unit: "quintal" },
  niger:    { category: "oilseed", baseYieldPerHa: 8,  unit: "quintal" },
  chia:     { category: "oilseed", baseYieldPerHa: 8,  unit: "quintal" },

  /* ===================== Vegetables ===================== */
  tomato:      { category: "vegetable", baseYieldPerHa: 30, unit: "tons" },
  potato:     { category: "vegetable", baseYieldPerHa: 25, unit: "tons" },
  onion:      { category: "vegetable", baseYieldPerHa: 20, unit: "tons" },
  garlic:     { category: "vegetable", baseYieldPerHa: 8,  unit: "tons" },
  brinjal:    { category: "vegetable", baseYieldPerHa: 28, unit: "tons" },
  cabbage:    { category: "vegetable", baseYieldPerHa: 35, unit: "tons" },
  cauliflower:{ category: "vegetable", baseYieldPerHa: 25, unit: "tons" },
  carrot:     { category: "vegetable", baseYieldPerHa: 30, unit: "tons" },
  beetroot:   { category: "vegetable", baseYieldPerHa: 25, unit: "tons" },
  radish:     { category: "vegetable", baseYieldPerHa: 30, unit: "tons" },
  cucumber:   { category: "vegetable", baseYieldPerHa: 20, unit: "tons" },
  pumpkin:    { category: "vegetable", baseYieldPerHa: 18, unit: "tons" },
  okra:       { category: "vegetable", baseYieldPerHa: 15, unit: "tons" },
  spinach:    { category: "vegetable", baseYieldPerHa: 12, unit: "tons" },
  lettuce:    { category: "vegetable", baseYieldPerHa: 10, unit: "tons" },
  capsicum:   { category: "vegetable", baseYieldPerHa: 20, unit: "tons" },
  broccoli:   { category: "vegetable", baseYieldPerHa: 18, unit: "tons" },
  bittergourd:{ category: "vegetable", baseYieldPerHa: 15, unit: "tons" },
  bottlegourd:{ category: "vegetable", baseYieldPerHa: 20, unit: "tons" },
  spongegourd:{ category: "vegetable", baseYieldPerHa: 18, unit: "tons" },
  ashgourd:   { category: "vegetable", baseYieldPerHa: 25, unit: "tons" },
  snakegourd: { category: "vegetable", baseYieldPerHa: 18, unit: "tons" },
  longmelon:  { category: "vegetable", baseYieldPerHa: 18, unit: "tons" },
  squashmelon:{ category: "vegetable", baseYieldPerHa: 20, unit: "tons" },
  summersquash:{ category: "vegetable", baseYieldPerHa: 18, unit: "tons" },
  sweetpotato:{ category: "vegetable", baseYieldPerHa: 20, unit: "tons" },
  turnip:     { category: "vegetable", baseYieldPerHa: 25, unit: "tons" },
  mushroom:   { category: "vegetable", baseYieldPerHa: 18, unit: "tons" },
  celery:    { category: "vegetable", baseYieldPerHa: 12, unit: "tons" },
  chilli:    { category: "vegetable", baseYieldPerHa: 12, unit: "tons" },
  drumstick: { category: "vegetable", baseYieldPerHa: 25, unit: "tons" },

  /* ===================== Fruits ===================== */
  banana:      { category: "fruit", baseYieldPerHa: 35, unit: "tons" },
  papaya:      { category: "fruit", baseYieldPerHa: 40, unit: "tons" },
  mango:       { category: "fruit", baseYieldPerHa: 10, unit: "tons" },
  guava:       { category: "fruit", baseYieldPerHa: 15, unit: "tons" },
  pomegranate: { category: "fruit", baseYieldPerHa: 12, unit: "tons" },
  grapes:      { category: "fruit", baseYieldPerHa: 20, unit: "tons" },
  watermelon:  { category: "fruit", baseYieldPerHa: 30, unit: "tons" },
  muskmelon:   { category: "fruit", baseYieldPerHa: 25, unit: "tons" },
  orange:      { category: "fruit", baseYieldPerHa: 18, unit: "tons" },
  sapota:      { category: "fruit", baseYieldPerHa: 10, unit: "tons" },
  fig:         { category: "fruit", baseYieldPerHa: 8,  unit: "tons" },
  apple:       { category: "fruit", baseYieldPerHa: 10, unit: "tons" },
  lemon:       { category: "fruit", baseYieldPerHa: 15, unit: "tons" },
  pineapple:   { category: "fruit", baseYieldPerHa: 45, unit: "tons" },
  kiwi:        { category: "fruit", baseYieldPerHa: 7,  unit: "tons" },
  amla:        { category: "fruit", baseYieldPerHa: 8,  unit: "tons" },
  dragonfruit: { category: "fruit", baseYieldPerHa: 20, unit: "tons" },

  /* ===================== Plantation & Spices ===================== */
  turmeric:    { category: "spice", baseYieldPerHa: 25, unit: "tons" },
  ginger:      { category: "spice", baseYieldPerHa: 20, unit: "tons" },
  coriander:   { category: "spice", baseYieldPerHa: 15, unit: "quintal" },
  cumin:       { category: "spice", baseYieldPerHa: 8,  unit: "quintal" },
  fenugreekmethi:{ category: "spice", baseYieldPerHa: 12, unit: "quintal" },
  blackpepper: { category: "plantation", baseYieldPerHa: 2, unit: "tons" },
  tea:         { category: "plantation", baseYieldPerHa: 2, unit: "tons" },
  coffee:      { category: "plantation", baseYieldPerHa: 1.5, unit: "tons" },
  coconut:     { category: "plantation", baseYieldPerHa: 10, unit: "tons" },
  arecanut:    { category: "plantation", baseYieldPerHa: 12, unit: "tons" },
  rubber:      { category: "plantation", baseYieldPerHa: 2, unit: "tons" },

  /* ===================== Commercial ===================== */
  sugarcane: { category: "cereal", baseYieldPerHa: 75, unit: "tons" },
  cotton:    { category: "oilseed", baseYieldPerHa: 20, unit: "quintal" },
  tobacco:   { category: "vegetable", baseYieldPerHa: 18, unit: "quintal" },
  jute:      { category: "cereal", baseYieldPerHa: 25, unit: "quintal" },

  /* ===================== Fallback ===================== */
  default: { category: "vegetable", baseYieldPerHa: 5, unit: "tons" },
};
